### ISSUE TITLE
Can't run the AppImage file on Arch Linux

### ISSUE THREAD

**Issue by oneohthree** [llamaret/MystiQ#17]
The AppImage file (version 0.2.0) throws this error on Arch Linux:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized.
Reinstalling the application may fix this problem.

Aborted (core dumped)
```

**Comment by llamaret** [comment]
right now we are, in the quiet of midnight, fixing the matter and correcting automation with travis

**Comment by stdevPavelmc** [comment]
@oneohthree that bug is solved, was the qt plugin, it was solved by commit https://github.com/llamaret/MystiQ/commit/fb90a6b8a6ff8737085183a35391007d37ff7b8d#diff-354f30a63fb0907d4ad57269548329e3 We are now battling with travis for the appimage release, and yet a new bug was found...

**Comment by stdevPavelmc** [comment]
It's safe to close this issue...
