### ISSUE TITLE
Problems with subtitle embedding

### ISSUE THREAD

**Issue by llamaret** [llamaret/MystiQ#22]
**Describe the bug**
When trying to activate the option to embed subtitle present in the same folder of the source video, the conversion fails. It is necessary to check if the subtitle embedding parameter was correctly declared in the class header related to the conversion parameters and review the implementation of the class

**Expected behavior**
The final result must be the successful conversion with the subtitle correctly embedded in the final video.

**Comment by dvillazon** [comment]
The conversion fails in **beta 4**.
**Os:** Win 10 64 bits

**Comment by lfdominguez** [comment]
> The conversion fails in **beta 4**.
> **Os:** Win 10 64 bits

Well you can say more about that?? error message or something?

**Comment by llamaret** [comment]
> > The conversion fails in **beta 4**.
> > **Os:** Win 10 64 bits
> 
> Well you can say more about that?? error message or something?

I tried to reproduce the error. And yes, in Windows the subtitle embedding fails. In GNU / Linux everything is fine, as planned. But since I saw this report, I tried on a windows 10 and yes, it failed. I have not had time to review.

**Comment by patrickelectric** [comment]
This should be fixed in 8edb3f29a3798c4851b8ef2474248ba3f5af1316
