### ISSUE TITLE
Error when no ffmpeg is found

### ISSUE THREAD

**Issue by glpzzz** [llamaret/MystiQ#28]
**Describe the bug**
When ffmpeg is not found it launches a error dialog with text "Not Found"

**To Reproduce**
Try to reproduce in and environment without ffmpeg

**Expected behavior**
Better error description: "ffmpeg is not found"
Also perhaps check for the presence of this in startup.

**Comment by llamaret** [comment]
> **Describe the bug**
> When ffmpeg is not found it launches a error dialog with text "Not Found"
> 
> **To Reproduce**
> Try to reproduce in and environment without ffmpeg
> 
> **Expected behavior**
> Better error description: "ffmpeg is not found"
> Also perhaps check for the presence of this in startup.

One of the first things that was added was the verification of the presence of the necessary binaries. If you run mystiq in an environment where ffmpeg / ffprobe / ffplay is not accessible, a message is displayed explaining the error, recommending installing ffmpeg and the application is closed.
Try to test yourself in an environment without ffmpeg
