### ISSUE TITLE
Add filename and output directory to Conversion parameters dialog

### ISSUE THREAD

**Issue by glpzzz** [llamaret/MystiQ#3]
#### Current behavior
Output filename and directory are also parameters of the conversion (where to store the result) but they arent in the Conversion parameters dialog, just in the Edit menu as two individual an unrelated action.

#### Expected behavior
To find the output variables in the Conversion parameters dialog

#### How to?
Add Output tab to Conversion parameters dialog and set this options there, also allow to select the format (if not selected when added this can't be configured again)

![image](https://user-images.githubusercontent.com/13596248/68081548-97ecf780-fddd-11e9-89f6-932110995cca.png)

**Comment by llamaret** [comment]
mmm, I liked your idea.
