### ISSUE TITLE
AppImage freezes when clicking on Edit in preset section

### ISSUE THREAD

**Issue by oneohthree** [llamaret/MystiQ#31]
1. Select file to convert
2. Click on 'Next'
3. Click on 'Edit' in preset section
4. The app crashes.

This is the log:

```
./MystiQ-x86_64-v20.01.09.AppImage
Reading file:  ":/other/constants.xml"
"Settings filename: /home/foo/.config/mystiq/AppRun.wrapped.ini"
"Set application path: /tmp/.mount_MystiQG3ONMB/usr/bin"
"Application Path: /tmp/.mount_MystiQG3ONMB/usr/bin"
"Data Path: "
"translationPath: /home/foo/translations"
Read FFmpeg Information
Reading preset file:  ":/other/presets.xml"
QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
QObject::connect: Cannot connect (null)::cut_up_changed(double) to ConversionParameterDialog::onCutUpChanged(double)
QObject::connect: Cannot connect (null)::cut_bottom_changed(double) to ConversionParameterDialog::onCutBottomChanged(double)
QObject::connect: Cannot connect (null)::cut_left_changed(double) to ConversionParameterDialog::onCutLeftChanged(double)
QObject::connect: Cannot connect (null)::cut_right_changed(double) to ConversionParameterDialog::onCutRightChanged(double)
QObject::connect: Cannot connect (null)::video_loaded(int,int) to ConversionParameterDialog::onVideoLoaded(int,int)
Segmentation fault (core dumped)
```

 - OS: Arch Linux
 - App Version: 20.01.09 (AppImage)

**Comment by llamaret** [comment]
That must be that we are lacking to package dependencies. We are reviewing the TravisCL script (which was now put in full slow mode)
Thanks for your report

**Comment by llamaret** [comment]
> Steps to reproduce the behavior:
> 
>     1. Select file to convert
> 
>     2. Click on 'Next'
> 
>     3. Click on 'Edit' in preset section
> 
>     4. The app crashes.
> 
> 
> This is the log:
> 
> ```
> ./MystiQ-x86_64-v20.01.09.AppImage
> Reading file:  ":/other/constants.xml"
> "Settings filename: /home/foo/.config/mystiq/AppRun.wrapped.ini"
> "Set application path: /tmp/.mount_MystiQG3ONMB/usr/bin"
> "Application Path: /tmp/.mount_MystiQG3ONMB/usr/bin"
> "Data Path: "
> "translationPath: /home/foo/translations"
> Read FFmpeg Information
> Reading preset file:  ":/other/presets.xml"
> QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
> QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> QObject::connect: Cannot connect (null)::cut_up_changed(double) to ConversionParameterDialog::onCutUpChanged(double)
> QObject::connect: Cannot connect (null)::cut_bottom_changed(double) to ConversionParameterDialog::onCutBottomChanged(double)
> QObject::connect: Cannot connect (null)::cut_left_changed(double) to ConversionParameterDialog::onCutLeftChanged(double)
> QObject::connect: Cannot connect (null)::cut_right_changed(double) to ConversionParameterDialog::onCutRightChanged(double)
> QObject::connect: Cannot connect (null)::video_loaded(int,int) to ConversionParameterDialog::onVideoLoaded(int,int)
> Segmentation fault (core dumped)
> ```
> 
>     * OS: Arch Linux
> 
>     * App Version: 20.01.09 (AppImage)

Please, try with this testing version
https://github.com/llamaret/MystiQ/releases/download/v20.01.20-dev/MystiQ_v20.01.20-dev.AppImage

**Comment by probonopd** [comment]
Looks like additional qml directories need to be passed to linuxdeployqt (if you are using that one).

**Comment by llamaret** [comment]
> Looks like additional qml directories need to be passed to linuxdeployqt (if you are using that one).

Hi Brother
You are just the person you can help us. If you could look at our .travis.yml and see that we are missing for the QML file to enter the resulting appimage file

**Comment by llamaret** [comment]
> Looks like additional qml directories need to be passed to linuxdeployqt (if you are using that one).

Can you Help Us? Please

**Comment by probonopd** [comment]
Well, first of all, it seems like you are building on bionic. Please build on no newer than xenial.

**Comment by llamaret** [comment]
> Well, first of all, it seems like you are building on bionic. Please build on no newer than xenial.

Now I am building with Xenial and same problem

**Comment by probonopd** [comment]
Is it possible to download the Xenial-built AppImage somewhere?

**Comment by probonopd** [comment]
Ah, just noticed you are using https://github.com/linuxdeploy/linuxdeploy-plugin-qt. According to its documentation, one needs to use

QML related:

* `$QML_SOURCES_PATHS`: directory containing the application's QML files -- useful/needed if QML files are "baked" into the binaries
* `$QML_MODULES_PATHS`: extra directories containing imported QML files (normally doesn't need to be specified)

So from reading that I would assume you need to export `QML_SOURCES_PATHS`, a comma-separated list of all directories that contain your qml files. Maybe @TheAssassin can comment.

**Comment by TheAssassin** [comment]
It's `$PATH`-style, so the separator is `:`. QML deployment cannot be fully automated, as one cannot tell the dependencies respectively their location from the binary. Therefore users have to provide some information.

Please feel free to file an issue over at our project if you need more assistance.

**Comment by llamaret** [comment]
> Is it possible to download the Xenial-built AppImage somewhere?

https://github.com/llamaret/MystiQ/releases/download/v20.02.15-AppImage/MystiQ_v20.02.15-x86_64.AppImage

**Comment by probonopd** [comment]
Getting

> FFmpeg or FFprobe  have not been found in the system. Please consider installing them before running MystiQ

They need to be bundled in the AppImage as well.

**Comment by probonopd** [comment]
Digging around with `strace` shows

```
me@host:~$ /home/me/Downloads/MystiQ_v20.02.15-x86_64.AppImage --appimage-extract

me@host:~$ find squashfs-root/ | grep -i multimedia
squashfs-root/usr/translations/qtmultimedia_zh_TW.qm
squashfs-root/usr/translations/qtmultimedia_uk.qm
squashfs-root/usr/translations/qtmultimedia_sk.qm
squashfs-root/usr/translations/qtmultimedia_ru.qm
squashfs-root/usr/translations/qtmultimedia_pl.qm
squashfs-root/usr/translations/qtmultimedia_ko.qm
squashfs-root/usr/translations/qtmultimedia_ja.qm
squashfs-root/usr/translations/qtmultimedia_it.qm
squashfs-root/usr/translations/qtmultimedia_hu.qm
squashfs-root/usr/translations/qtmultimedia_fr.qm
squashfs-root/usr/translations/qtmultimedia_fi.qm
squashfs-root/usr/translations/qtmultimedia_es.qm
squashfs-root/usr/translations/qtmultimedia_en.qm
squashfs-root/usr/translations/qtmultimedia_de.qm
squashfs-root/usr/translations/qtmultimedia_da.qm
squashfs-root/usr/translations/qtmultimedia_cs.qm
squashfs-root/usr/translations/qtmultimedia_ca.qm
squashfs-root/usr/translations/qtmultimedia_bg.qm
squashfs-root/usr/translations/qtmultimedia_ar.qm
squashfs-root/usr/share/doc/qt512multimedia
squashfs-root/usr/share/doc/qt512multimedia/copyright
squashfs-root/usr/lib/libQt5MultimediaWidgets.so.5
squashfs-root/usr/lib/libQt5MultimediaGstTools.so.5
squashfs-root/usr/lib/libQt5Multimedia.so.5
```

**Comment by probonopd** [comment]
Went ahead and experimented a bit with a still-experimental tool of mine, it produced this:
https://github.com/probonopd/MystiQ/releases

Interestingly it also complains about

```
qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
```

even though the following files are present (and according to `strace` are queried):

```
./opt/qt512/qml/QtQuick.2
./opt/qt512/qml/QtQuick.2/qmldir
./opt/qt512/qml/QtQuick.2/plugins.qmltypes
./opt/qt512/qml/QtQuick.2/libqtquick2plugin.so
./opt/qt512/qml/QtMultimedia
./opt/qt512/qml/QtMultimedia/qmldir
./opt/qt512/qml/QtMultimedia/plugins.qmltypes
./opt/qt512/qml/QtMultimedia/libdeclarative_multimedia.so
./opt/qt512/qml/QtMultimedia/Video.qml
```

I am puzzled here. Probably we need a Qt/QML expert that can explain what is going on here...

**Comment by llamaret** [comment]
> Went ahead and experimented a bit with a still-experimental tool of mine, it produced this:
> https://github.com/probonopd/MystiQ/releases
> 
> Check its `.travis.yml`, it's quite a bit shorter and more streamlined:
> https://github.com/probonopd/MystiQ/blob/patch-1/.travis.yml
> 
> The following files are present (and according to `strace` are queried):
> 
> ```
> ./opt/qt512/qml/QtQuick.2
> ./opt/qt512/qml/QtQuick.2/qmldir
> ./opt/qt512/qml/QtQuick.2/plugins.qmltypes
> ./opt/qt512/qml/QtQuick.2/libqtquick2plugin.so
> ./opt/qt512/qml/QtMultimedia
> ./opt/qt512/qml/QtMultimedia/qmldir
> ./opt/qt512/qml/QtMultimedia/plugins.qmltypes
> ./opt/qt512/qml/QtMultimedia/libdeclarative_multimedia.so
> ./opt/qt512/qml/QtMultimedia/Video.qml
> ```
> 
> **I consider these files to be necessary, so that's progress... but seemingly not enough?!**
> 
> Also note that FFmpeg is correctly found inside the AppImage.
> 
> Interestingly it also crashes at the same point, also complaining about
> 
> ```
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> ```
> 
> When running with
> 
> ```
>  '/home/me/Downloads/MystiQ_Video_Converter-16-x86_64.AppImage' --appimage-extract
>  LD_DEBUG=libs squashfs-root/AppRun 
> ```
> 
> I see
> 
> ```
> QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
> QLayout: Attempting to add QLayout "" to TimeRangeEdit "", which already has a layout
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_stats (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_clear (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_enable (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_disable (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_push_location (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_pop_location (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_save (fatal)
>       8088:	/home/me/squashfs-root/usr/bin/../../opt/qt512/lib/./libQt5Qml.so.5: error: symbol lookup error: undefined symbol: qmlmemprofile_is_enabled (fatal)
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> qrc:/qml/main.qml:1:1: module "QtQuick" is not installed
> qrc:/qml/main.qml:2:1: module "QtMultimedia" is not installed
> QObject::connect: Cannot connect (null)::cut_up_changed(double) to ConversionParameterDialog::onCutUpChanged(double)
> QObject::connect: Cannot connect (null)::cut_bottom_changed(double) to ConversionParameterDialog::onCutBottomChanged(double)
> QObject::connect: Cannot connect (null)::cut_left_changed(double) to ConversionParameterDialog::onCutLeftChanged(double)
> QObject::connect: Cannot connect (null)::cut_right_changed(double) to ConversionParameterDialog::onCutRightChanged(double)
> QObject::connect: Cannot connect (null)::video_loaded(int,int) to ConversionParameterDialog::onVideoLoaded(int,int)
> Segmentation fault
> ```
> 
> at the point where the crash happens.
> 
> I am puzzled here. Probably we need a Qt/QML expert that can explain what is going on here...
> 
> Do we need to deploy more from `/opt/qt512/qml/`?

Perhaps the error is due to the fact that we are using a variant of Qt5 from a PPA. This PPA does not install in the usual location (/ usr / ....) but in / opt
If Bionic could be used, the KDE Neon Qt5 could be used, if it locates the packages in the expected location. Because the app needs Qt5> 5.10

**Comment by probonopd** [comment]
> Perhaps the error is due to the fact that we are using a variant of Qt5 from a PPA.

As long as we are not mixing up the PPA version with non-PPA stuff it _should_ work just fine...

What you could test is run a xenial Live ISO or VM and install the same Qt there and build MystiQ there, then see whether the same crash occurs in the non-AppImage version... just in case. Although I would expect that to work.

**Comment by probonopd** [comment]
I quickly did a test build on Bionic with the KDE Neon Qt5 - same issue. So that would _not_ solve it.

**Comment by llamaret** [comment]
> I quickly did a test build on Bionic with the KDE Neon Qt5 - same issue. So that would _not_ solve it.

:(

**Comment by llamaret** [comment]
Thanks to @azubieta now MystiQ has a functional AppImage. Thanks to @probonopd y @TheAssassin  too. So, closing Issue
