### ISSUE TITLE
Unclear error message appear.

### ISSUE THREAD

**Issue by crixero** [llamaret/MystiQ#33]
**Describe the bug**
When  running .appimage with locales set to es_CU without FFmpeg on the host system it return  a unclear  error message.

**To Reproduce**
1. Have a Ubuntu 18.04.3 system without FFmpeg installed
2. Run Mystiq.appimage version 20.01.20
3. The error message should appear
4. See error: "No encontrado"

**Expected behavior**
The program should inform the user that he need to install FFmpeg on the host OS clearly.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/58792563/72555566-d0439400-386a-11ea-9783-93857f70d9a3.png)

**Desktop:**
 - OS: [Ubuntu 18.04.3]
 - MystiQ Version  [20.01.20]

**Comment by llamaret** [comment]
Fixing

**Comment by llamaret** [comment]
> Fixing although it is strange that that happened from the Appimage, because the appimage already includes the FFMpeg binary, regardless of whether the system includes it

Fixed the Error Message. And, to future releases, we'll include static ffmpeg into appimage package
