### ISSUE TITLE
qt5-default

### ISSUE THREAD

**Issue by eson57** [llamaret/MystiQ#46]
Cant't install the deb package because of qt5-default >=5.10.0 dependency.
Most LTS distributions don't have that new qt5.

 - OS: Linux Mint 19.3 (Ubuntu 18.04)

**Comment by lfdominguez** [comment]
The problem is that MystiQ is using some function that are only on >=5.10.0, use the AppImage for distributions where doesnt have that version of Qt

**Comment by eson57** [comment]
Yes, that's what I'm doing already. Thanks for explaining anyway.
