### ISSUE TITLE
Install via 'make install'

### ISSUE THREAD

**Issue by stdevPavelmc** [llamaret/MystiQ#7]
Actually the project has no option to install the bins via a makefile target.

I will fork and work on it holiday style

**Comment by llamaret** [comment]
Any collaboration is appreciated. I am a tyrannosaurus of those that with cp solves, but it is clear that this takes make install. All his way of the make install, at your own pace. welcome

**Comment by stdevPavelmc** [comment]
Reading here: https://doc-snapshots.qt.io/qt5-5.9/qmake-advanced-usage.html I see that we need to pass a additional makefile target on the project file.

Work will be directed to that option.

**Comment by stdevPavelmc** [comment]
Closed by #13
